MvcForum/MvcForum/Models/Tag.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MvcForum.Models
{
    public class Tag
    {
        public int TagId { get; set; }
        public string TagName { get; set; }


        public List<PostTag> PostTags { get; set; }

    }
}

MvcForum/MvcForum/Controllers/TagController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MvcForum.Models;
using MvcForum.ViewModel;

namespace MvcForum.Controllers
{
    [Route("api/ABCDE")]
    [ApiController]
    public class TagController : ControllerBase
    {
        private readonly ForumContext _context;

        public TagController(ForumContext context)
        {
            _context = context;

            if (_context.Tags.Count() == 0)
            {
                // Create a new TodoItem if collection is empty,
                // which means you can't delete all TodoItems.
                _context.Tags.Add(new Tag { TagName = "happy" });
                _context.SaveChanges();
            }

        }
        [HttpGet]
        public async Task<ActionResult<IEnumerable<TagVm>>> GetTag()
        {
            var tag = _context.Tags
                  .Include(t => t.PostTags)
                 .OrderBy(t => t.TagId)
                   .Select(t => new TagVm
                   {
                       TagId = t.TagId,
                       TagName = t.TagName,
                       post = t.PostTags.Select(f => new uuPostVm { PostId = f.Post.PostId, HeadLine = f.Post.HeadLine }).ToList()
                   })
                 .ToList();
            return tag;
        }

        [HttpGet("{id}")]
        public async Task<ActionResult<TagVm>> GetTag(int id)
        {

            var item = await _context.Tags.FindAsync(id);

            if (item == null)
            {
                return NotFound();
            }
            else
            {

                var tag = _context.Tags
                     .Include(t => t.PostTags)
                    .OrderBy(u => u.TagId)
                   .Select(t => new TagVm
                   {
                       TagId = t.TagId,
                       TagName = t.TagName,
                       post = t.PostTags.Select(f => new uuPostVm { PostId = f.Post.PostId, HeadLine = f.Post.HeadLine }).ToList()
                   })
                    .ToList();


                return tag.Find(t => t.TagId == id);
            }


        }
        [HttpPost]
        public async Task<ActionResult<Tag>> PostTag(Tag tag)
        {
            _context.PostTag.Add(tag.PostTags.First());

            _context.Tags.Add(tag);

            await _context.SaveChangesAsync();

            return CreatedAtAction(nameof(GetTag), new { id = tag.TagId }, tag);
        }
        [HttpDelete("{id}")]
        public async Task<IActionResult> DeleteTag(int id)
        {
            var item = await _context.Tags.FindAsync(id);

            if (item == null)
            {
                return NotFound();
            }

            _context.Tags.Remove(item);
            await _context.SaveChangesAsync();

            return NoContent();
        }
        [HttpPut("{id}")]
        public async Task<IActionResult> PutTag(int id, Tag tag)
        {
            if (id != tag.TagId)
            {
                return BadRequest();
            }


            _context.Entry(tag).State = EntityState.Modified;


            await _context.SaveChangesAsync();

            return NoContent();
        }


    }
}

MvcForum/MvcForum/Controllers/TagsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MvcForum.Models;
using MvcForum.ViewModel;

namespace MvcForum.Controllers
{
    public class TagsController : Controller
    {
        private readonly ForumContext _context;

        public TagsController(ForumContext context)
        {
            _context = context;
        }

        // GET: Tags
        public async Task<IActionResult> Index(String searchstring)
        {
            var tags = from f in _context.Tags
                         select f;
            if (!String.IsNullOrEmpty(searchstring))
            {
                tags = tags.Where(s => s.TagName.Contains(searchstring));
            }
            return View(await tags.ToListAsync());
        }

        // GET: Tags/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var tag = _context.Tags
                  .Include(t => t.PostTags)
                 .OrderBy(t => t.TagId)
                   .Select(t => new TagVm
                   {
                       TagId = t.TagId,
                       TagName = t.TagName,
                       post = t.PostTags.Select(f => new uuPostVm { PostId = f.Post.PostId, HeadLine = f.Post.HeadLine }).ToList()
                   }).FirstOrDefault(t=>t.TagId==id);
                 

            if (tag == null)
            {
                return NotFound();
            }

            return View(tag);
        }

        // GET: Tags/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Tags/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("TagId,TagName")] Tag tag)
        {
            if (ModelState.IsValid)
            {
                _context.Add(tag);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(tag);
        }

        // GET: Tags/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tag = await _context.Tags.FindAsync(id);
            if (tag == null)
            {
                return NotFound();
            }
            return View(tag);
        }

        // POST: Tags/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("TagId,TagName")] Tag tag)
        {
            if (id != tag.TagId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(tag);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TagExists(tag.TagId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(tag);
        }

        // GET: Tags/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tag = await _context.Tags
                .FirstOrDefaultAsync(m => m.TagId == id);
            if (tag == null)
            {
                return NotFound();
            }

            return View(tag);
        }

        // POST: Tags/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var tag = await _context.Tags.FindAsync(id);
            _context.Tags.Remove(tag);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TagExists(int id)
        {
            return _context.Tags.Any(e => e.TagId == id);
        }
    }
}

MvcForum/MvcForum/Views/Tags/Create.cshtml
@model MvcForum.Models.Tag

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Tag</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="TagName" class="control-label"></label>
                <input asp-for="TagName" class="form-control" />
                <span asp-validation-for="TagName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MvcForum/MvcForum/Views/Tags/Delete.cshtml
@model MvcForum.Models.Tag

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Tag</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TagName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TagName)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="TagId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

MvcForum/MvcForum/Views/Tags/Details.cshtml
@model MvcForum.ViewModel.TagVm

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Tag</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.TagName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.TagName)
        </dd>
        @foreach (var item in Model.post)
        {
            <dt class="col-sm-2">
                @Html.DisplayNameFor(modelitem => item.PostId)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(modelitem => item.PostId)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(modelitem => item.HeadLine)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(modelitem => item.HeadLine)
            </dd>

        }
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.TagId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

MvcForum/MvcForum/Views/Tags/Edit.cshtml
@model MvcForum.Models.Tag

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Tag</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="TagId" />
            <div class="form-group">
                <label asp-for="TagName" class="control-label"></label>
                <input asp-for="TagName" class="form-control" />
                <span asp-validation-for="TagName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MvcForum/MvcForum/Views/Tags/Index.cshtml
@model IEnumerable<MvcForum.Models.Tag>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<form asp-controller="Tags" asp-action="Index">
    <p>
        Title: <input type="text" name="searchstring">
        <input type="submit" value="Filter" />
    </p>
</form>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.TagName)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.TagName)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.TagId">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.TagId">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.TagId">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>