MvcForum/MvcForum/Models/Forum.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MvcForum.Models
{
    public class Forum
    {
        public int ForumId { get; set; }
        public string ForumName { get; set; }
        public string Abbreviation { get; set; }

        public List<UserForum> UsersForums { get; set; }

        public List<Post> Posts { get; set; }
    }
}

MvcForum/MvcForum/Controllers/ForumController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MvcForum.Models;
using MvcForum.ViewModel;

namespace MvcForum.Controllers
{
    [Route("api/ABCD")]
    [ApiController]
    public class ForumController : ControllerBase
    {
        private readonly ForumContext _context;

        public ForumController(ForumContext context)
        {
            _context = context;

            if (_context.Forum1s.Count() == 0)
            {
                // Create a new TodoItem if collection is empty,
                // which means you can't delete all TodoItems.
                _context.Forum1s.Add(new Forum { ForumName = "AAA", Abbreviation = "aa" });
                _context.SaveChanges();
            }

        }
        [HttpGet]
        public async Task<ActionResult<IEnumerable<ForumVm>>> GetForum()
        {
            var forum = _context.Forum1s
              .Include(f => f.UsersForums)
              .Include(f => f.Posts)
              .OrderBy(f => f.ForumId)
               .Select(f => new ForumVm
               {
                   ForumId = f.ForumId,
                   ForumName = f.ForumName,
                   posts = f.Posts.Select(p => new uPostVm
                   {
                       PostId = p.PostId,
                       HeadLine = p.HeadLine,
                       Link = p.Link

                   }).ToList(),
                   users = f.UsersForums.Select(u => new uUserVm { UserName = u.User.UserName, UserId = u.User.UserId }).ToList()
               })
               .ToList();

            return forum;
        }

        [HttpGet("{id}")]
        public async Task<ActionResult<ForumVm>> GetForum(int id)
        {

            var item = await _context.Forum1s.FindAsync(id);

            if (item == null)
            {
                return NotFound();
            }

            else
            {
                var forum = _context.Forum1s
                  .Include(f => f.UsersForums)
                  .Include(f => f.Posts)
                  .OrderBy(f => f.ForumId)
               .Select(f => new ForumVm
               {
                   ForumId = f.ForumId,
                   ForumName = f.ForumName,
                   posts = f.Posts.Select(p => new uPostVm
                   {
                       PostId = p.PostId,
                       HeadLine = p.HeadLine,
                       Link = p.Link

                   }).ToList(),
                   users = f.UsersForums.Select(u => new uUserVm { UserName = u.User.UserName, UserId = u.User.UserId }).ToList()
               })
                  .ToList();


                return forum.Find(u => u.ForumId == id);
            }
        }
        [HttpPost]
        public async Task<ActionResult<Forum>> PostForum(Forum forum)
        {


            _context.Forum1s.Add(forum);

            //_context.UserForum.Add(forum.UsersForums.First());

            await _context.SaveChangesAsync();

            return CreatedAtAction(nameof(GetForum), new { id = forum.ForumId }, forum);
        }
        [HttpDelete("{id}")]
        public async Task<IActionResult> DeleteTodoItem(int id)
        {
            var item = await _context.Forum1s.FindAsync(id);

            if (item == null)
            {
                return NotFound();
            }

            _context.Forum1s.Remove(item);
            await _context.SaveChangesAsync();

            return NoContent();
        }
        [HttpPut("{id}")]
        public async Task<IActionResult> PutForumItem(int id, Forum item)
        {
            if (id != item.ForumId)
            {
                return BadRequest();
            }

            _context.Entry(item).State = EntityState.Modified;
            await _context.SaveChangesAsync();

            return NoContent();
        }


    }
}

MvcForum/MvcForum/Controllers/ForumsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MvcForum.Models;
using MvcForum.ViewModel;

namespace MvcForum.Controllers
{
    public class ForumsController : Controller
    {
        private readonly ForumContext _context;

        public ForumsController(ForumContext context)
        {
            _context = context;
        }

        // GET: Forums
        public async Task<IActionResult> Index(String searchstring)
        {
            var forums = from f in _context.Forum1s
                        select f;
            if (!String.IsNullOrEmpty(searchstring))
            {
                forums = forums.Where(s => s.ForumName.Contains(searchstring));
            }



            return View(await forums.ToListAsync());
        }

        // GET: Forums/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var forum = _context.Forum1s
                             .Include(f => f.UsersForums)
                             .Include(f => f.Posts)
                             .OrderBy(f => f.ForumId)
                          .Select(f => new ForumVm
                          {
                              ForumId = f.ForumId,
                              ForumName = f.ForumName,
                              posts = f.Posts.Select(p => new uPostVm
                              {
                                  PostId = p.PostId,
                                  HeadLine = p.HeadLine,
                                  Link = p.Link

                              }).ToList(),
                              users = f.UsersForums.Select(u => new uUserVm { UserName = u.User.UserName, UserId = u.User.UserId }).ToList()
                          }).FirstOrDefault(m => m.ForumId == id);
                             
                
               
            if (forum == null)
            {
                return NotFound();
            }

            return View(forum);
        }

        // GET: Forums/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Forums/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ForumId,ForumName,Abbreviation")] Forum forum)
        {
            if (ModelState.IsValid)
            {
                _context.Add(forum);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(forum);
        }

        // GET: Forums/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var forum = await _context.Forum1s.FindAsync(id);
            if (forum == null)
            {
                return NotFound();
            }
            return View(forum);
        }

        // POST: Forums/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ForumId,ForumName,Abbreviation")] Forum forum)
        {
            if (id != forum.ForumId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(forum);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ForumExists(forum.ForumId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(forum);
        }

        // GET: Forums/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var forum = await _context.Forum1s
                .FirstOrDefaultAsync(m => m.ForumId == id);
            if (forum == null)
            {
                return NotFound();
            }

            return View(forum);
        }

        // POST: Forums/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var forum = await _context.Forum1s.FindAsync(id);
            _context.Forum1s.Remove(forum);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ForumExists(int id)
        {
            return _context.Forum1s.Any(e => e.ForumId == id);
        }
    }
}

MvcForum/MvcForum/Views/Forums/Create.cshtml
@model MvcForum.Models.Forum

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Forum</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="ForumName" class="control-label"></label>
                <input asp-for="ForumName" class="form-control" />
                <span asp-validation-for="ForumName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Abbreviation" class="control-label"></label>
                <input asp-for="Abbreviation" class="form-control" />
                <span asp-validation-for="Abbreviation" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MvcForum/MvcForum/Views/Forums/Delete.cshtml
@model MvcForum.Models.Forum

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Forum</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ForumName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ForumName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Abbreviation)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Abbreviation)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ForumId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

MvcForum/MvcForum/Views/Forums/Details.cshtml
@model MvcForum.ViewModel.ForumVm

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Forum</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ForumId)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ForumId)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ForumName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ForumName)
        </dd>
        @foreach (var item in Model.posts)
        {
            <dt class="col-sm-2">
                @Html.DisplayNameFor(modelItem => item.PostId)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(modelItem => item.PostId)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(modelItem => item.HeadLine)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(modelItem => item.HeadLine)
            </dd>

        }
        @foreach (var aa in Model.users)
        {
            <dt class="col-sm-2">
                @Html.DisplayNameFor(modelaa => aa.UserId)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(modelaa => aa.UserId)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(modelaa => aa.UserName)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(modelaa => aa.UserName)
            </dd>
        }
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.ForumId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

MvcForum/MvcForum/Views/Forums/Edit.cshtml
@model MvcForum.Models.Forum

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Forum</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ForumId" />
            <div class="form-group">
                <label asp-for="ForumName" class="control-label"></label>
                <input asp-for="ForumName" class="form-control" />
                <span asp-validation-for="ForumName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Abbreviation" class="control-label"></label>
                <input asp-for="Abbreviation" class="form-control" />
                <span asp-validation-for="Abbreviation" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MvcForum/MvcForum/Views/Forums/Index.cshtml
@model IEnumerable<MvcForum.Models.Forum>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<form asp-controller="Forums" asp-action="Index">
    <p>
        Title: <input type="text" name="searchstring">
        <input type="submit" value="Filter" />
    </p>
</form>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.ForumName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Abbreviation)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.ForumName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Abbreviation)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.ForumId">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.ForumId">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.ForumId">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>